### PR TITLE
Finish Domains page

### LINKED ISSUE #9: Build domains page

### PR DESCRIPTION
**Pull request by jasonappah**
image

This is just using dummy data, but using actual API routes should just need some changes in the `getServerSideProps` call. Lmk if anything needs updating or fixing

Closes #9

### CODE REVIEW

**Comment by jasonappah** [comment]
Closes #9

**Comment by cjdenio** [comment]
Looks great!

**Comment by jasonappah** [comment]
orange-eel-43 loca lt_apps_pog_domains

I forgot to include the add domain input, so I've added that and also a little warning message for when domains are already connected to other apps.

**Comment by anirudhb** [comment]
Just fyi I'm probably gonna delay approving this PR until we have the existing API ported to the new infrastructure.

**Comment by jasonappah** [comment]
Sounds good to me

**Comment by jasonappah** [comment]
looks like caleb got this with cb34cfb so i'll close :)

**Pull request closed without merging**
